[2022-11-27T10:04:59.264+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: saham_one_time_historical.insert_table_saham manual__2022-11-27T10:04:12.444922+00:00 [queued]>
[2022-11-27T10:04:59.320+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: saham_one_time_historical.insert_table_saham manual__2022-11-27T10:04:12.444922+00:00 [queued]>
[2022-11-27T10:04:59.324+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-27T10:04:59.327+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 4
[2022-11-27T10:04:59.466+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-27T10:04:59.808+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): insert_table_saham> on 2022-11-27 10:04:12.444922+00:00
[2022-11-27T10:04:59.858+0000] {standard_task_runner.py:55} INFO - Started process 868 to run task
[2022-11-27T10:04:59.940+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'saham_one_time_historical', 'insert_table_saham', 'manual__2022-11-27T10:04:12.444922+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/one_time_historical_dag.py', '--cfg-path', '/tmp/tmpftsv6gvv']
[2022-11-27T10:05:00.008+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask insert_table_saham
[2022-11-27T10:05:04.799+0000] {task_command.py:376} INFO - Running <TaskInstance: saham_one_time_historical.insert_table_saham manual__2022-11-27T10:04:12.444922+00:00 [running]> on host 3cef85d75852
[2022-11-27T10:05:07.706+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kcb kelompok
AIRFLOW_CTX_DAG_ID=saham_one_time_historical
AIRFLOW_CTX_TASK_ID=insert_table_saham
AIRFLOW_CTX_EXECUTION_DATE=2022-11-27T10:04:12.444922+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-27T10:04:12.444922+00:00
[2022-11-27T10:05:57.973+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/one_time_historical/extract_dim_saham.py", line 53, in insertStockListData
    data = getstocklistData()
  File "/opt/airflow/one_time_historical/extract_dim_saham.py", line 19, in getstocklistData
    data = get_scrap_data(URL)
  File "/opt/airflow/one_time_historical/utils.py", line 52, in get_scrap_data
    content = browser.find_element(By.TAG_NAME, "pre").text
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}
  (Session info: headless chrome=107.0.5304.87)
Stacktrace:
#0 0x5611faa63463 <unknown>
#1 0x5611fa8278d8 <unknown>
#2 0x5611fa86543a <unknown>
#3 0x5611fa865651 <unknown>
#4 0x5611fa8a17a4 <unknown>
#5 0x5611fa88664d <unknown>
#6 0x5611fa89f30f <unknown>
#7 0x5611fa886443 <unknown>
#8 0x5611fa8573c5 <unknown>
#9 0x5611fa858531 <unknown>
#10 0x5611faab5dce <unknown>
#11 0x5611faab9192 <unknown>
#12 0x5611faa9a93e <unknown>
#13 0x5611faaba103 <unknown>
#14 0x5611faa8dd85 <unknown>
#15 0x5611faadb0a8 <unknown>
#16 0x5611faadb239 <unknown>
#17 0x5611faaf6492 <unknown>
#18 0x7feb33aa0609 start_thread

[2022-11-27T10:05:58.077+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=saham_one_time_historical, task_id=insert_table_saham, execution_date=20221127T100412, start_date=20221127T100459, end_date=20221127T100558
[2022-11-27T10:05:58.154+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 25 for task insert_table_saham (Message: no such element: Unable to locate element: {"method":"tag name","selector":"pre"}
  (Session info: headless chrome=107.0.5304.87)
Stacktrace:
#0 0x5611faa63463 <unknown>
#1 0x5611fa8278d8 <unknown>
#2 0x5611fa86543a <unknown>
#3 0x5611fa865651 <unknown>
#4 0x5611fa8a17a4 <unknown>
#5 0x5611fa88664d <unknown>
#6 0x5611fa89f30f <unknown>
#7 0x5611fa886443 <unknown>
#8 0x5611fa8573c5 <unknown>
#9 0x5611fa858531 <unknown>
#10 0x5611faab5dce <unknown>
#11 0x5611faab9192 <unknown>
#12 0x5611faa9a93e <unknown>
#13 0x5611faaba103 <unknown>
#14 0x5611faa8dd85 <unknown>
#15 0x5611faadb0a8 <unknown>
#16 0x5611faadb239 <unknown>
#17 0x5611faaf6492 <unknown>
#18 0x7feb33aa0609 start_thread
; 868)
[2022-11-27T10:05:58.274+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-27T10:05:58.507+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
